/*
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Orch8AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/orchestr8_test/parser/antlr/internal/InternalOrch8.tokens");
	}
}
