/*
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.orchestr8_test.parser.antlr.internal.InternalOrch8Parser;
import org.xtext.orchestr8_test.services.Orch8GrammarAccess;

public class Orch8Parser extends AbstractAntlrParser {

	@Inject
	private Orch8GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOrch8Parser createParser(XtextTokenStream stream) {
		return new InternalOrch8Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Orch8GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Orch8GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
