/*
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Orch8RuntimeModule extends AbstractOrch8RuntimeModule {
}
