/*
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

import Orchestr8.Orchestr8Package;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Orch8StandaloneSetup extends Orch8StandaloneSetupGenerated {

	public static void doSetup() {
		new Orch8StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	// added this
	// maybe its the google injector? -> it was
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("")) {
			EPackage.Registry.INSTANCE.put("", Orchestr8Package.eINSTANCE);
		}
		super.register(injector);
	}
}
