/*
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class Orch8OutlineTreeProvider extends DefaultOutlineTreeProvider {

}
