/*
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Orch8UiModule extends AbstractOrch8UiModule {

	public Orch8UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
