/*
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.orchestr8_test.ui.internal.Orchestr8_testActivator;

public class Orch8UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Orchestr8_testActivator.getInstance().getInjector("org.xtext.orchestr8_test.Orch8");
	}

}
