/*
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test.formatting2

import Orchestr8.Model
import Orchestr8.Score
import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.xtext.orchestr8_test.services.Orch8GrammarAccess

class Orch8Formatter extends AbstractFormatter2 {
	
	@Inject extension Orch8GrammarAccess

	def dispatch void format(Model model, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (score : model.scores) {
			score.format
		}
		for (instrument : model.instruments) {
			instrument.format
		}
		model.mixer.format
	}

	def dispatch void format(Score score, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (command : score.setup) {
			command.format
		}
		for (measure : score.measures) {
			measure.format
		}
		for (command : score.end) {
			command.format
		}
	}
	
	// TODO: implement for Instrument, Measure, CmdInstrument, Beat
}
