/**
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test.tests;

import Orchestr8.Model;
import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(Orch8InjectorProvider.class)
@SuppressWarnings("all")
public class Orch8ParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  @Test
  public void smallestValidProgram() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Score my_score {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(":1.0");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("play e4 length 1.0");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("Mixer my_mixer {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("scores { my_score }");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void noMixer() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Score my_score {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(":1.0");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("play e4 length 1.0");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("There should be errors");
      Assertions.assertFalse(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void noMeasures() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Score my_score {}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("Mixer my_mixer {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("scores { my_score }");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("There should be errors");
      Assertions.assertFalse(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void noScores() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Mixer my_mixer {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("scores {}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("There should be errors");
      Assertions.assertFalse(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void outOfPlaceSetup() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Score my_score {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(":1.0");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("play e4 length 1.0");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@Setup");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("instrument volume 1.0");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("Mixer my_mixer {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("scores { my_score }");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("There should be errors");
      Assertions.assertFalse(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void incompletePlayCmd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Score my_score {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(":1.0");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("play e4");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("Mixer my_mixer {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("scores { my_score }");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("There should be errors");
      Assertions.assertFalse(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void stringParameter() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Score my_score {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@Setup");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("instrument volume \"heloo\"");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("Mixer my_mixer {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("scores { my_score }");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("There should be errors");
      Assertions.assertFalse(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void multipleMeasures() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Score my_score {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(":1.0");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("play e4 length 2.0");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(":1.0");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("instrument volume 0.5");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("Mixer my_mixer {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("scores { my_score }");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unknown errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
