/*
 * generated by Xtext 2.26.0
 */
grammar InternalOrch8;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package org.xtext.orchestr8_test.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.xtext.orchestr8_test.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import org.xtext.orchestr8_test.services.Orch8GrammarAccess;

}
@parser::members {
	private Orch8GrammarAccess grammarAccess;

	public void setGrammarAccess(Orch8GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleModel
entryRuleModel
:
{ before(grammarAccess.getModelRule()); }
	 ruleModel
{ after(grammarAccess.getModelRule()); } 
	 EOF 
;

// Rule Model
ruleModel 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getModelAccess().getGroup()); }
		(rule__Model__Group__0)
		{ after(grammarAccess.getModelAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleSetupCommand
entryRuleSetupCommand
:
{ before(grammarAccess.getSetupCommandRule()); }
	 ruleSetupCommand
{ after(grammarAccess.getSetupCommandRule()); } 
	 EOF 
;

// Rule SetupCommand
ruleSetupCommand 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getSetupCommandAccess().getAlternatives()); }
		(rule__SetupCommand__Alternatives)
		{ after(grammarAccess.getSetupCommandAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCommand
entryRuleCommand
:
{ before(grammarAccess.getCommandRule()); }
	 ruleCommand
{ after(grammarAccess.getCommandRule()); } 
	 EOF 
;

// Rule Command
ruleCommand 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCommandAccess().getAlternatives()); }
		(rule__Command__Alternatives)
		{ after(grammarAccess.getCommandAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMixer
entryRuleMixer
:
{ before(grammarAccess.getMixerRule()); }
	 ruleMixer
{ after(grammarAccess.getMixerRule()); } 
	 EOF 
;

// Rule Mixer
ruleMixer 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMixerAccess().getGroup()); }
		(rule__Mixer__Group__0)
		{ after(grammarAccess.getMixerAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleScore
entryRuleScore
:
{ before(grammarAccess.getScoreRule()); }
	 ruleScore
{ after(grammarAccess.getScoreRule()); } 
	 EOF 
;

// Rule Score
ruleScore 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getScoreAccess().getGroup()); }
		(rule__Score__Group__0)
		{ after(grammarAccess.getScoreAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleInstrument
entryRuleInstrument
:
{ before(grammarAccess.getInstrumentRule()); }
	 ruleInstrument
{ after(grammarAccess.getInstrumentRule()); } 
	 EOF 
;

// Rule Instrument
ruleInstrument 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getInstrumentAccess().getGroup()); }
		(rule__Instrument__Group__0)
		{ after(grammarAccess.getInstrumentAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEString
entryRuleEString
:
{ before(grammarAccess.getEStringRule()); }
	 ruleEString
{ after(grammarAccess.getEStringRule()); } 
	 EOF 
;

// Rule EString
ruleEString 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEStringAccess().getAlternatives()); }
		(rule__EString__Alternatives)
		{ after(grammarAccess.getEStringAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEInt
entryRuleEInt
:
{ before(grammarAccess.getEIntRule()); }
	 ruleEInt
{ after(grammarAccess.getEIntRule()); } 
	 EOF 
;

// Rule EInt
ruleEInt 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEIntAccess().getGroup()); }
		(rule__EInt__Group__0)
		{ after(grammarAccess.getEIntAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEDouble
entryRuleEDouble
:
{ before(grammarAccess.getEDoubleRule()); }
	 ruleEDouble
{ after(grammarAccess.getEDoubleRule()); } 
	 EOF 
;

// Rule EDouble
ruleEDouble 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEDoubleAccess().getGroup()); }
		(rule__EDouble__Group__0)
		{ after(grammarAccess.getEDoubleAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMeasure
entryRuleMeasure
:
{ before(grammarAccess.getMeasureRule()); }
	 ruleMeasure
{ after(grammarAccess.getMeasureRule()); } 
	 EOF 
;

// Rule Measure
ruleMeasure 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMeasureAccess().getGroup()); }
		(rule__Measure__Group__0)
		{ after(grammarAccess.getMeasureAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCmdInstrument
entryRuleCmdInstrument
:
{ before(grammarAccess.getCmdInstrumentRule()); }
	 ruleCmdInstrument
{ after(grammarAccess.getCmdInstrumentRule()); } 
	 EOF 
;

// Rule CmdInstrument
ruleCmdInstrument 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCmdInstrumentAccess().getGroup()); }
		(rule__CmdInstrument__Group__0)
		{ after(grammarAccess.getCmdInstrumentAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCmdPlay
entryRuleCmdPlay
:
{ before(grammarAccess.getCmdPlayRule()); }
	 ruleCmdPlay
{ after(grammarAccess.getCmdPlayRule()); } 
	 EOF 
;

// Rule CmdPlay
ruleCmdPlay 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCmdPlayAccess().getGroup()); }
		(rule__CmdPlay__Group__0)
		{ after(grammarAccess.getCmdPlayAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCmdTempo
entryRuleCmdTempo
:
{ before(grammarAccess.getCmdTempoRule()); }
	 ruleCmdTempo
{ after(grammarAccess.getCmdTempoRule()); } 
	 EOF 
;

// Rule CmdTempo
ruleCmdTempo 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCmdTempoAccess().getGroup()); }
		(rule__CmdTempo__Group__0)
		{ after(grammarAccess.getCmdTempoAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCmdTimeSignature
entryRuleCmdTimeSignature
:
{ before(grammarAccess.getCmdTimeSignatureRule()); }
	 ruleCmdTimeSignature
{ after(grammarAccess.getCmdTimeSignatureRule()); } 
	 EOF 
;

// Rule CmdTimeSignature
ruleCmdTimeSignature 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCmdTimeSignatureAccess().getGroup()); }
		(rule__CmdTimeSignature__Group__0)
		{ after(grammarAccess.getCmdTimeSignatureAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCmdSet
entryRuleCmdSet
:
{ before(grammarAccess.getCmdSetRule()); }
	 ruleCmdSet
{ after(grammarAccess.getCmdSetRule()); } 
	 EOF 
;

// Rule CmdSet
ruleCmdSet 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCmdSetAccess().getGroup()); }
		(rule__CmdSet__Group__0)
		{ after(grammarAccess.getCmdSetAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleParameter
entryRuleParameter
:
{ before(grammarAccess.getParameterRule()); }
	 ruleParameter
{ after(grammarAccess.getParameterRule()); } 
	 EOF 
;

// Rule Parameter
ruleParameter 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getParameterAccess().getGroup()); }
		(rule__Parameter__Group__0)
		{ after(grammarAccess.getParameterAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleBeat
entryRuleBeat
:
{ before(grammarAccess.getBeatRule()); }
	 ruleBeat
{ after(grammarAccess.getBeatRule()); } 
	 EOF 
;

// Rule Beat
ruleBeat 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getBeatAccess().getGroup()); }
		(rule__Beat__Group__0)
		{ after(grammarAccess.getBeatAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleGenerator
entryRuleGenerator
:
{ before(grammarAccess.getGeneratorRule()); }
	 ruleGenerator
{ after(grammarAccess.getGeneratorRule()); } 
	 EOF 
;

// Rule Generator
ruleGenerator 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getGeneratorAccess().getGroup()); }
		(rule__Generator__Group__0)
		{ after(grammarAccess.getGeneratorAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Alternatives_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getScoresAssignment_0_0()); }
		(rule__Model__ScoresAssignment_0_0)
		{ after(grammarAccess.getModelAccess().getScoresAssignment_0_0()); }
	)
	|
	(
		{ before(grammarAccess.getModelAccess().getInstrumentsAssignment_0_1()); }
		(rule__Model__InstrumentsAssignment_0_1)
		{ after(grammarAccess.getModelAccess().getInstrumentsAssignment_0_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Alternatives_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getScoresAssignment_2_0()); }
		(rule__Model__ScoresAssignment_2_0)
		{ after(grammarAccess.getModelAccess().getScoresAssignment_2_0()); }
	)
	|
	(
		{ before(grammarAccess.getModelAccess().getInstrumentsAssignment_2_1()); }
		(rule__Model__InstrumentsAssignment_2_1)
		{ after(grammarAccess.getModelAccess().getInstrumentsAssignment_2_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__SetupCommand__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSetupCommandAccess().getCmdTempoParserRuleCall_0()); }
		ruleCmdTempo
		{ after(grammarAccess.getSetupCommandAccess().getCmdTempoParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getSetupCommandAccess().getCmdTimeSignatureParserRuleCall_1()); }
		ruleCmdTimeSignature
		{ after(grammarAccess.getSetupCommandAccess().getCmdTimeSignatureParserRuleCall_1()); }
	)
	|
	(
		{ before(grammarAccess.getSetupCommandAccess().getCmdInstrumentParserRuleCall_2()); }
		ruleCmdInstrument
		{ after(grammarAccess.getSetupCommandAccess().getCmdInstrumentParserRuleCall_2()); }
	)
	|
	(
		{ before(grammarAccess.getSetupCommandAccess().getCmdSetParserRuleCall_3()); }
		ruleCmdSet
		{ after(grammarAccess.getSetupCommandAccess().getCmdSetParserRuleCall_3()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Command__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCommandAccess().getCmdTempoParserRuleCall_0()); }
		ruleCmdTempo
		{ after(grammarAccess.getCommandAccess().getCmdTempoParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getCommandAccess().getCmdTimeSignatureParserRuleCall_1()); }
		ruleCmdTimeSignature
		{ after(grammarAccess.getCommandAccess().getCmdTimeSignatureParserRuleCall_1()); }
	)
	|
	(
		{ before(grammarAccess.getCommandAccess().getCmdPlayParserRuleCall_2()); }
		ruleCmdPlay
		{ after(grammarAccess.getCommandAccess().getCmdPlayParserRuleCall_2()); }
	)
	|
	(
		{ before(grammarAccess.getCommandAccess().getCmdInstrumentParserRuleCall_3()); }
		ruleCmdInstrument
		{ after(grammarAccess.getCommandAccess().getCmdInstrumentParserRuleCall_3()); }
	)
	|
	(
		{ before(grammarAccess.getCommandAccess().getCmdSetParserRuleCall_4()); }
		ruleCmdSet
		{ after(grammarAccess.getCommandAccess().getCmdSetParserRuleCall_4()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EString__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
		RULE_STRING
		{ after(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
		RULE_ID
		{ after(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Alternatives_4_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEDoubleAccess().getEKeyword_4_0_0()); }
		'E'
		{ after(grammarAccess.getEDoubleAccess().getEKeyword_4_0_0()); }
	)
	|
	(
		{ before(grammarAccess.getEDoubleAccess().getEKeyword_4_0_1()); }
		'e'
		{ after(grammarAccess.getEDoubleAccess().getEKeyword_4_0_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Generator__ModeAlternatives_0_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getGeneratorAccess().getModeTypeKeyword_0_0_0()); }
		'type'
		{ after(grammarAccess.getGeneratorAccess().getModeTypeKeyword_0_0_0()); }
	)
	|
	(
		{ before(grammarAccess.getGeneratorAccess().getModeCustomKeyword_0_0_1()); }
		'custom'
		{ after(grammarAccess.getGeneratorAccess().getModeCustomKeyword_0_0_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__0__Impl
	rule__Model__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getAlternatives_0()); }
	(rule__Model__Alternatives_0)*
	{ after(grammarAccess.getModelAccess().getAlternatives_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__1__Impl
	rule__Model__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getMixerAssignment_1()); }
	(rule__Model__MixerAssignment_1)
	{ after(grammarAccess.getModelAccess().getMixerAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getAlternatives_2()); }
	(rule__Model__Alternatives_2)*
	{ after(grammarAccess.getModelAccess().getAlternatives_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Mixer__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__0__Impl
	rule__Mixer__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getMixerKeyword_0()); }
	'Mixer'
	{ after(grammarAccess.getMixerAccess().getMixerKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__1__Impl
	rule__Mixer__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getNameAssignment_1()); }
	(rule__Mixer__NameAssignment_1)
	{ after(grammarAccess.getMixerAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__2__Impl
	rule__Mixer__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getMixerAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__3__Impl
	rule__Mixer__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getGroup_3()); }
	(rule__Mixer__Group_3__0)?
	{ after(grammarAccess.getMixerAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__4__Impl
	rule__Mixer__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getScoresKeyword_4()); }
	'scores'
	{ after(grammarAccess.getMixerAccess().getScoresKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__5__Impl
	rule__Mixer__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getLeftCurlyBracketKeyword_5()); }
	'{'
	{ after(grammarAccess.getMixerAccess().getLeftCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__6__Impl
	rule__Mixer__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getScoresAssignment_6()); }
	(rule__Mixer__ScoresAssignment_6)
	{ after(grammarAccess.getMixerAccess().getScoresAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__7__Impl
	rule__Mixer__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getGroup_7()); }
	(rule__Mixer__Group_7__0)*
	{ after(grammarAccess.getMixerAccess().getGroup_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__8__Impl
	rule__Mixer__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getRightCurlyBracketKeyword_8()); }
	'}'
	{ after(grammarAccess.getMixerAccess().getRightCurlyBracketKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group__9__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getRightCurlyBracketKeyword_9()); }
	'}'
	{ after(grammarAccess.getMixerAccess().getRightCurlyBracketKeyword_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Mixer__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group_3__0__Impl
	rule__Mixer__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getSampling_rateKeyword_3_0()); }
	'sampling_rate'
	{ after(grammarAccess.getMixerAccess().getSampling_rateKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getSampling_rateAssignment_3_1()); }
	(rule__Mixer__Sampling_rateAssignment_3_1)
	{ after(grammarAccess.getMixerAccess().getSampling_rateAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Mixer__Group_7__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group_7__0__Impl
	rule__Mixer__Group_7__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group_7__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getCommaKeyword_7_0()); }
	','
	{ after(grammarAccess.getMixerAccess().getCommaKeyword_7_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group_7__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Mixer__Group_7__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Group_7__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMixerAccess().getScoresAssignment_7_1()); }
	(rule__Mixer__ScoresAssignment_7_1)
	{ after(grammarAccess.getMixerAccess().getScoresAssignment_7_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Score__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group__0__Impl
	rule__Score__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getScoreKeyword_0()); }
	'Score'
	{ after(grammarAccess.getScoreAccess().getScoreKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group__1__Impl
	rule__Score__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getNameAssignment_1()); }
	(rule__Score__NameAssignment_1)
	{ after(grammarAccess.getScoreAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group__2__Impl
	rule__Score__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getScoreAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group__3__Impl
	rule__Score__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getGroup_3()); }
	(rule__Score__Group_3__0)?
	{ after(grammarAccess.getScoreAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group__4__Impl
	rule__Score__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getScoreAccess().getMeasuresAssignment_4()); }
		(rule__Score__MeasuresAssignment_4)
		{ after(grammarAccess.getScoreAccess().getMeasuresAssignment_4()); }
	)
	(
		{ before(grammarAccess.getScoreAccess().getMeasuresAssignment_4()); }
		(rule__Score__MeasuresAssignment_4)*
		{ after(grammarAccess.getScoreAccess().getMeasuresAssignment_4()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group__5__Impl
	rule__Score__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getGroup_5()); }
	(rule__Score__Group_5__0)?
	{ after(grammarAccess.getScoreAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getRightCurlyBracketKeyword_6()); }
	'}'
	{ after(grammarAccess.getScoreAccess().getRightCurlyBracketKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Score__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group_3__0__Impl
	rule__Score__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getSetupKeyword_3_0()); }
	'@Setup'
	{ after(grammarAccess.getScoreAccess().getSetupKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getSetupAssignment_3_1()); }
	(rule__Score__SetupAssignment_3_1)*
	{ after(grammarAccess.getScoreAccess().getSetupAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Score__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group_5__0__Impl
	rule__Score__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getEndKeyword_5_0()); }
	'@End'
	{ after(grammarAccess.getScoreAccess().getEndKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Score__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getScoreAccess().getEndAssignment_5_1()); }
	(rule__Score__EndAssignment_5_1)*
	{ after(grammarAccess.getScoreAccess().getEndAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Instrument__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Instrument__Group__0__Impl
	rule__Instrument__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstrumentAccess().getInstrumentKeyword_0()); }
	'Instrument'
	{ after(grammarAccess.getInstrumentAccess().getInstrumentKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Instrument__Group__1__Impl
	rule__Instrument__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstrumentAccess().getNameAssignment_1()); }
	(rule__Instrument__NameAssignment_1)
	{ after(grammarAccess.getInstrumentAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Instrument__Group__2__Impl
	rule__Instrument__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstrumentAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getInstrumentAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Instrument__Group__3__Impl
	rule__Instrument__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstrumentAccess().getGeneratorAssignment_3()); }
	(rule__Instrument__GeneratorAssignment_3)
	{ after(grammarAccess.getInstrumentAccess().getGeneratorAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Instrument__Group__4__Impl
	rule__Instrument__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstrumentAccess().getParametersAssignment_4()); }
	(rule__Instrument__ParametersAssignment_4)*
	{ after(grammarAccess.getInstrumentAccess().getParametersAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Instrument__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstrumentAccess().getRightCurlyBracketKeyword_5()); }
	'}'
	{ after(grammarAccess.getInstrumentAccess().getRightCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EInt__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EInt__Group__0__Impl
	rule__EInt__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getEIntAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EInt__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntAccess().getINTTerminalRuleCall_1()); }
	RULE_INT
	{ after(grammarAccess.getEIntAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EDouble__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDouble__Group__0__Impl
	rule__EDouble__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getEDoubleAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDouble__Group__1__Impl
	rule__EDouble__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_1()); }
	(RULE_INT)?
	{ after(grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDouble__Group__2__Impl
	rule__EDouble__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleAccess().getFullStopKeyword_2()); }
	'.'
	{ after(grammarAccess.getEDoubleAccess().getFullStopKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDouble__Group__3__Impl
	rule__EDouble__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_3()); }
	RULE_INT
	{ after(grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDouble__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleAccess().getGroup_4()); }
	(rule__EDouble__Group_4__0)?
	{ after(grammarAccess.getEDoubleAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EDouble__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDouble__Group_4__0__Impl
	rule__EDouble__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleAccess().getAlternatives_4_0()); }
	(rule__EDouble__Alternatives_4_0)
	{ after(grammarAccess.getEDoubleAccess().getAlternatives_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDouble__Group_4__1__Impl
	rule__EDouble__Group_4__2
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleAccess().getHyphenMinusKeyword_4_1()); }
	('-')?
	{ after(grammarAccess.getEDoubleAccess().getHyphenMinusKeyword_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group_4__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDouble__Group_4__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EDouble__Group_4__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_4_2()); }
	RULE_INT
	{ after(grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_4_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Measure__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Measure__Group__0__Impl
	rule__Measure__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Measure__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMeasureAccess().getMeasureAction_0()); }
	()
	{ after(grammarAccess.getMeasureAccess().getMeasureAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Measure__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Measure__Group__1__Impl
	rule__Measure__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Measure__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMeasureAccess().getCommercialAtKeyword_1()); }
	'@'
	{ after(grammarAccess.getMeasureAccess().getCommercialAtKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Measure__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Measure__Group__2__Impl
	rule__Measure__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Measure__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMeasureAccess().getIDAssignment_2()); }
	(rule__Measure__IDAssignment_2)
	{ after(grammarAccess.getMeasureAccess().getIDAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Measure__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Measure__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Measure__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getMeasureAccess().getBeatsAssignment_3()); }
		(rule__Measure__BeatsAssignment_3)
		{ after(grammarAccess.getMeasureAccess().getBeatsAssignment_3()); }
	)
	(
		{ before(grammarAccess.getMeasureAccess().getBeatsAssignment_3()); }
		(rule__Measure__BeatsAssignment_3)*
		{ after(grammarAccess.getMeasureAccess().getBeatsAssignment_3()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}


rule__CmdInstrument__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdInstrument__Group__0__Impl
	rule__CmdInstrument__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdInstrument__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdInstrumentAccess().getTypeAssignment_0()); }
	(rule__CmdInstrument__TypeAssignment_0)
	{ after(grammarAccess.getCmdInstrumentAccess().getTypeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdInstrument__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdInstrument__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdInstrument__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdInstrumentAccess().getParameterAssignment_1()); }
	(rule__CmdInstrument__ParameterAssignment_1)
	{ after(grammarAccess.getCmdInstrumentAccess().getParameterAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__CmdPlay__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdPlay__Group__0__Impl
	rule__CmdPlay__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdPlayAccess().getTypeAssignment_0()); }
	(rule__CmdPlay__TypeAssignment_0)
	{ after(grammarAccess.getCmdPlayAccess().getTypeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdPlay__Group__1__Impl
	rule__CmdPlay__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdPlayAccess().getNoteAssignment_1()); }
	(rule__CmdPlay__NoteAssignment_1)
	{ after(grammarAccess.getCmdPlayAccess().getNoteAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdPlay__Group__2__Impl
	rule__CmdPlay__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdPlayAccess().getLengthKeyword_2()); }
	'length'
	{ after(grammarAccess.getCmdPlayAccess().getLengthKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdPlay__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdPlayAccess().getLengthAssignment_3()); }
	(rule__CmdPlay__LengthAssignment_3)
	{ after(grammarAccess.getCmdPlayAccess().getLengthAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__CmdTempo__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdTempo__Group__0__Impl
	rule__CmdTempo__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTempo__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdTempoAccess().getTypeAssignment_0()); }
	(rule__CmdTempo__TypeAssignment_0)
	{ after(grammarAccess.getCmdTempoAccess().getTypeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTempo__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdTempo__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTempo__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdTempoAccess().getBpmAssignment_1()); }
	(rule__CmdTempo__BpmAssignment_1)
	{ after(grammarAccess.getCmdTempoAccess().getBpmAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__CmdTimeSignature__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdTimeSignature__Group__0__Impl
	rule__CmdTimeSignature__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdTimeSignatureAccess().getTypeAssignment_0()); }
	(rule__CmdTimeSignature__TypeAssignment_0)
	{ after(grammarAccess.getCmdTimeSignatureAccess().getTypeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdTimeSignature__Group__1__Impl
	rule__CmdTimeSignature__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdTimeSignatureAccess().getNumeratorAssignment_1()); }
	(rule__CmdTimeSignature__NumeratorAssignment_1)
	{ after(grammarAccess.getCmdTimeSignatureAccess().getNumeratorAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdTimeSignature__Group__2__Impl
	rule__CmdTimeSignature__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdTimeSignatureAccess().getSolidusKeyword_2()); }
	'/'
	{ after(grammarAccess.getCmdTimeSignatureAccess().getSolidusKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdTimeSignature__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdTimeSignatureAccess().getDenominatorAssignment_3()); }
	(rule__CmdTimeSignature__DenominatorAssignment_3)
	{ after(grammarAccess.getCmdTimeSignatureAccess().getDenominatorAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__CmdSet__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdSet__Group__0__Impl
	rule__CmdSet__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdSet__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdSetAccess().getTypeAssignment_0()); }
	(rule__CmdSet__TypeAssignment_0)
	{ after(grammarAccess.getCmdSetAccess().getTypeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdSet__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__CmdSet__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdSet__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCmdSetAccess().getInstrumentAssignment_1()); }
	(rule__CmdSet__InstrumentAssignment_1)
	{ after(grammarAccess.getCmdSetAccess().getInstrumentAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Parameter__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Parameter__Group__0__Impl
	rule__Parameter__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Parameter__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getParameterAccess().getIDAssignment_0()); }
	(rule__Parameter__IDAssignment_0)
	{ after(grammarAccess.getParameterAccess().getIDAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Parameter__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Parameter__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Parameter__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getParameterAccess().getValueAssignment_1()); }
	(rule__Parameter__ValueAssignment_1)
	{ after(grammarAccess.getParameterAccess().getValueAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Beat__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Beat__Group__0__Impl
	rule__Beat__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Beat__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBeatAccess().getColonKeyword_0()); }
	':'
	{ after(grammarAccess.getBeatAccess().getColonKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Beat__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Beat__Group__1__Impl
	rule__Beat__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Beat__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBeatAccess().getIDAssignment_1()); }
	(rule__Beat__IDAssignment_1)
	{ after(grammarAccess.getBeatAccess().getIDAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Beat__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Beat__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Beat__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getBeatAccess().getCommandsAssignment_2()); }
		(rule__Beat__CommandsAssignment_2)
		{ after(grammarAccess.getBeatAccess().getCommandsAssignment_2()); }
	)
	(
		{ before(grammarAccess.getBeatAccess().getCommandsAssignment_2()); }
		(rule__Beat__CommandsAssignment_2)*
		{ after(grammarAccess.getBeatAccess().getCommandsAssignment_2()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Generator__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Generator__Group__0__Impl
	rule__Generator__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Generator__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getGeneratorAccess().getModeAssignment_0()); }
	(rule__Generator__ModeAssignment_0)
	{ after(grammarAccess.getGeneratorAccess().getModeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Generator__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Generator__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Generator__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getGeneratorAccess().getTypeAssignment_1()); }
	(rule__Generator__TypeAssignment_1)
	{ after(grammarAccess.getGeneratorAccess().getTypeAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Model__ScoresAssignment_0_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getScoresScoreParserRuleCall_0_0_0()); }
		ruleScore
		{ after(grammarAccess.getModelAccess().getScoresScoreParserRuleCall_0_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__InstrumentsAssignment_0_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getInstrumentsInstrumentParserRuleCall_0_1_0()); }
		ruleInstrument
		{ after(grammarAccess.getModelAccess().getInstrumentsInstrumentParserRuleCall_0_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__MixerAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getMixerMixerParserRuleCall_1_0()); }
		ruleMixer
		{ after(grammarAccess.getModelAccess().getMixerMixerParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__ScoresAssignment_2_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getScoresScoreParserRuleCall_2_0_0()); }
		ruleScore
		{ after(grammarAccess.getModelAccess().getScoresScoreParserRuleCall_2_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__InstrumentsAssignment_2_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getInstrumentsInstrumentParserRuleCall_2_1_0()); }
		ruleInstrument
		{ after(grammarAccess.getModelAccess().getInstrumentsInstrumentParserRuleCall_2_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMixerAccess().getNameEStringParserRuleCall_1_0()); }
		ruleEString
		{ after(grammarAccess.getMixerAccess().getNameEStringParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__Sampling_rateAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMixerAccess().getSampling_rateEIntParserRuleCall_3_1_0()); }
		ruleEInt
		{ after(grammarAccess.getMixerAccess().getSampling_rateEIntParserRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__ScoresAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMixerAccess().getScoresScoreCrossReference_6_0()); }
		(
			{ before(grammarAccess.getMixerAccess().getScoresScoreEStringParserRuleCall_6_0_1()); }
			ruleEString
			{ after(grammarAccess.getMixerAccess().getScoresScoreEStringParserRuleCall_6_0_1()); }
		)
		{ after(grammarAccess.getMixerAccess().getScoresScoreCrossReference_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Mixer__ScoresAssignment_7_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMixerAccess().getScoresScoreCrossReference_7_1_0()); }
		(
			{ before(grammarAccess.getMixerAccess().getScoresScoreEStringParserRuleCall_7_1_0_1()); }
			ruleEString
			{ after(grammarAccess.getMixerAccess().getScoresScoreEStringParserRuleCall_7_1_0_1()); }
		)
		{ after(grammarAccess.getMixerAccess().getScoresScoreCrossReference_7_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getScoreAccess().getNameEStringParserRuleCall_1_0()); }
		ruleEString
		{ after(grammarAccess.getScoreAccess().getNameEStringParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__SetupAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getScoreAccess().getSetupSetupCommandParserRuleCall_3_1_0()); }
		ruleSetupCommand
		{ after(grammarAccess.getScoreAccess().getSetupSetupCommandParserRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__MeasuresAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getScoreAccess().getMeasuresMeasureParserRuleCall_4_0()); }
		ruleMeasure
		{ after(grammarAccess.getScoreAccess().getMeasuresMeasureParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Score__EndAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getScoreAccess().getEndSetupCommandParserRuleCall_5_1_0()); }
		ruleSetupCommand
		{ after(grammarAccess.getScoreAccess().getEndSetupCommandParserRuleCall_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInstrumentAccess().getNameEStringParserRuleCall_1_0()); }
		ruleEString
		{ after(grammarAccess.getInstrumentAccess().getNameEStringParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__GeneratorAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInstrumentAccess().getGeneratorGeneratorParserRuleCall_3_0()); }
		ruleGenerator
		{ after(grammarAccess.getInstrumentAccess().getGeneratorGeneratorParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Instrument__ParametersAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInstrumentAccess().getParametersParameterParserRuleCall_4_0()); }
		ruleParameter
		{ after(grammarAccess.getInstrumentAccess().getParametersParameterParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Measure__IDAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMeasureAccess().getIDEIntParserRuleCall_2_0()); }
		ruleEInt
		{ after(grammarAccess.getMeasureAccess().getIDEIntParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Measure__BeatsAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMeasureAccess().getBeatsBeatParserRuleCall_3_0()); }
		ruleBeat
		{ after(grammarAccess.getMeasureAccess().getBeatsBeatParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdInstrument__TypeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdInstrumentAccess().getTypeInstrumentKeyword_0_0()); }
		(
			{ before(grammarAccess.getCmdInstrumentAccess().getTypeInstrumentKeyword_0_0()); }
			'instrument'
			{ after(grammarAccess.getCmdInstrumentAccess().getTypeInstrumentKeyword_0_0()); }
		)
		{ after(grammarAccess.getCmdInstrumentAccess().getTypeInstrumentKeyword_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdInstrument__ParameterAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdInstrumentAccess().getParameterParameterParserRuleCall_1_0()); }
		ruleParameter
		{ after(grammarAccess.getCmdInstrumentAccess().getParameterParameterParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__TypeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdPlayAccess().getTypePlayKeyword_0_0()); }
		(
			{ before(grammarAccess.getCmdPlayAccess().getTypePlayKeyword_0_0()); }
			'play'
			{ after(grammarAccess.getCmdPlayAccess().getTypePlayKeyword_0_0()); }
		)
		{ after(grammarAccess.getCmdPlayAccess().getTypePlayKeyword_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__NoteAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdPlayAccess().getNoteNOTETerminalRuleCall_1_0()); }
		RULE_NOTE
		{ after(grammarAccess.getCmdPlayAccess().getNoteNOTETerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdPlay__LengthAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdPlayAccess().getLengthEDoubleParserRuleCall_3_0()); }
		ruleEDouble
		{ after(grammarAccess.getCmdPlayAccess().getLengthEDoubleParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTempo__TypeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdTempoAccess().getTypeTempoKeyword_0_0()); }
		(
			{ before(grammarAccess.getCmdTempoAccess().getTypeTempoKeyword_0_0()); }
			'tempo'
			{ after(grammarAccess.getCmdTempoAccess().getTypeTempoKeyword_0_0()); }
		)
		{ after(grammarAccess.getCmdTempoAccess().getTypeTempoKeyword_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTempo__BpmAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdTempoAccess().getBpmEIntParserRuleCall_1_0()); }
		ruleEInt
		{ after(grammarAccess.getCmdTempoAccess().getBpmEIntParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__TypeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdTimeSignatureAccess().getTypeTime_signatureKeyword_0_0()); }
		(
			{ before(grammarAccess.getCmdTimeSignatureAccess().getTypeTime_signatureKeyword_0_0()); }
			'time_signature'
			{ after(grammarAccess.getCmdTimeSignatureAccess().getTypeTime_signatureKeyword_0_0()); }
		)
		{ after(grammarAccess.getCmdTimeSignatureAccess().getTypeTime_signatureKeyword_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__NumeratorAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdTimeSignatureAccess().getNumeratorEIntParserRuleCall_1_0()); }
		ruleEInt
		{ after(grammarAccess.getCmdTimeSignatureAccess().getNumeratorEIntParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdTimeSignature__DenominatorAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdTimeSignatureAccess().getDenominatorEIntParserRuleCall_3_0()); }
		ruleEInt
		{ after(grammarAccess.getCmdTimeSignatureAccess().getDenominatorEIntParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdSet__TypeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdSetAccess().getTypeSetKeyword_0_0()); }
		(
			{ before(grammarAccess.getCmdSetAccess().getTypeSetKeyword_0_0()); }
			'set'
			{ after(grammarAccess.getCmdSetAccess().getTypeSetKeyword_0_0()); }
		)
		{ after(grammarAccess.getCmdSetAccess().getTypeSetKeyword_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__CmdSet__InstrumentAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCmdSetAccess().getInstrumentInstrumentCrossReference_1_0()); }
		(
			{ before(grammarAccess.getCmdSetAccess().getInstrumentInstrumentEStringParserRuleCall_1_0_1()); }
			ruleEString
			{ after(grammarAccess.getCmdSetAccess().getInstrumentInstrumentEStringParserRuleCall_1_0_1()); }
		)
		{ after(grammarAccess.getCmdSetAccess().getInstrumentInstrumentCrossReference_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Parameter__IDAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getParameterAccess().getIDEStringParserRuleCall_0_0()); }
		ruleEString
		{ after(grammarAccess.getParameterAccess().getIDEStringParserRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Parameter__ValueAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getParameterAccess().getValueEDoubleParserRuleCall_1_0()); }
		ruleEDouble
		{ after(grammarAccess.getParameterAccess().getValueEDoubleParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Beat__IDAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBeatAccess().getIDEDoubleParserRuleCall_1_0()); }
		ruleEDouble
		{ after(grammarAccess.getBeatAccess().getIDEDoubleParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Beat__CommandsAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBeatAccess().getCommandsCommandParserRuleCall_2_0()); }
		ruleCommand
		{ after(grammarAccess.getBeatAccess().getCommandsCommandParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Generator__ModeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getGeneratorAccess().getModeAlternatives_0_0()); }
		(rule__Generator__ModeAlternatives_0_0)
		{ after(grammarAccess.getGeneratorAccess().getModeAlternatives_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Generator__TypeAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getGeneratorAccess().getTypeEStringParserRuleCall_1_0()); }
		ruleEString
		{ after(grammarAccess.getGeneratorAccess().getTypeEStringParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_NOTE : ('a'..'g'|'A'..'G') ('b'|'#')? '0'..'9';

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
