/*
 * generated by Xtext 2.26.0
 */
package org.xtext.orchestr8_test.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOrch8ScopeProvider extends DelegatingScopeProvider {
}
